# Site settings
title: Jameson Nyeholt
email: jnyeholt@hey.com
description: > # this means to ignore newlines until "baseurl:"
  Jameson Nyeholt's weblog.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "http://jamesonnyeholt.com" # the base hostname & protocol for your site
twitter_username: jwnyeholt
github_username:  wintermuted

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: true
disqus_shortname: advantxgarde

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

permalink: /:year/:month/:day/:title.html

sass:
  sass_dir: _sass
  style: compressed

collections_dir: collections

plugins:
  - jekyll-archives

jekyll-archives:
  enabled: all
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: category-archive
    tag: tag-archive

collections:
  software_development:
    output: true
  cascadia:
    output: true
  category:
    output: false
  tag: 
    output: false

include:
 - tags
 - favicon.ico
