name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master # or master before October 2020

jobs:
  github-pages:
    runs-on: ubuntu-latest
    build_only: true
    pre_build_commands:
      # - apk --update add imagemagick
      # - apk add  libarchive-tools 
      - apk --no-cache add vips-tools
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        